### ISSUE TITLE
Transfer to Sprints repo

### ISSUE THREAD

**Issue by allisonletts** [Nickers3/OutboundFundsGAU#4]
Hi @Nickers3  - 
As I've been working on the community sprint repo, I'm realizing that it would be really helpful to have this repo in the same place as all of our issues--merging PRs and closing issues are pretty related. What do you think? I can't remember why we were separating this out.

I don't think it's a good idea to try to move this over to the SFDO-run repo, but this repo seems like the primary work we'll be doing for a bit in (and between) sprints.
Allison

**Comment by Nickers3** [comment]
@allisonletts you may be onto something here.  The one concern I have would be that at future sprints we'll be working on new items and would likely need a free repo to start from.  I wonder if we can create a sub repo.  I'll send Cori a note to get her thoughts on how we could setup Github.

**Comment by Nickers3** [comment]
@allisonletts I heard back from Cori and her recommendation was to merge this over to the sprint.  I'll do the merge over the weekend.
